/*
 *
 *    Copyright 1996-2026 Traction Software, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 */

// PLEASE DO NOT DELETE THIS LINE - make copyright depends on it.

package com.tractionsoftware.commons.xml;

import com.tractionsoftware.commons.config.Configuration;
import com.tractionsoftware.commons.config.ConfigurationException;
import com.tractionsoftware.commons.config.ConfiguredObject;
import com.tractionsoftware.commons.util.ReloadingSupplier;
import jakarta.annotation.Nonnull;
import org.xml.sax.SAXException;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Templates;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import java.io.File;
import java.io.IOException;
import java.util.Date;

/**
 * XslFileTransformer is a JaxXsltTransformer class that uses the XSL file specified in its configuration as the source
 * of the XSL document for its javax.xml.transform.Transformer.
 *
 * <p>
 * Because Transformer objects are not thread safe, but Templates objects are thread safe, this class caches a Templates
 * object generated by processing an XSL document, and uses that to generate the Transformer that is used each time. If
 * "transformer" debug logging is enabled, the cached Templates object will be refreshed each time the transform method
 * is invoked.
 *
 * @author Dave Shepperton
 * @since 4.0
 */
public final class XslFileTextTransformer extends JaxpXsltTextTransformer {

    private static final String PROP_NAME_XSL_FILE_PATH = "xsl_file_path";

    private final class TemplatesSupplier extends ReloadingSupplier<Templates> {

        private TemplatesSupplier(Templates templates, Date loadTime) {
            super(templates, loadTime);
        }

        @Override
        public final String toDebugString() {
            return XslFileTextTransformer.this.toDebugString();
        }

        @Override
        protected final Date getResourceLastModifiedDate() {
            return new Date(XslFileTextTransformer.this.xslFile.lastModified());
        }

        @Override
        protected final Templates reload() {
            return XslFileTextTransformer.this.loadTemplates();
        }

    }

    /**
     * Set during setConfiguration, this File refers to the XSL document file on disk.
     */
    private final File xslFile;

    private final TemplatesSupplier templates;

    public XslFileTextTransformer(Configuration config) {
        super(config);
        this.xslFile = new File(
            ConfiguredObject.getRequiredNonBlankProperty(config, PROP_NAME_XSL_FILE_PATH).trim()
        );
        Date loadTime = new Date();
        this.templates = new TemplatesSupplier(loadTemplates(), loadTime);
        createTransformer();
    }

    public final String toDebugString() {
        return this + ":" + xslFile;
    }

    /**
     * Returns the javax.xml.transform.Transformer derived from interpreting the XSL document contained in the file
     * named by the "xsl_file_path" property of this Transformer's configuration.
     *
     * @return the javax.xml.transform.Transformer derived from interpreting the XSL document contained in the file
     *     named by the "xsl_file_path" property of this Transformer's configuration.
     */
    @Nonnull
    @Override
    protected final javax.xml.transform.Transformer getJaxpTransformer() throws IOException {
        return createTransformer();
    }

    private final Templates loadTemplates() {
        try {
            return JaxpUtil.getTemplates(xslFile);
        }
        catch (ConfigurationException e) {
            throw e;
        }
        catch (TransformerConfigurationException |
               IOException |
               SAXException |
               ParserConfigurationException |
               RuntimeException e) {
            throw new ConfigurationException("Failed to create a transformer from the file " + xslFile + ".", e);
        }
    }

    private final Transformer createTransformer() {
        try {
            return JaxpUtil.getTransformer(templates.get(), LOGGER);
        }
        catch (ConfigurationException e) {
            throw e;
        }
        catch (TransformerConfigurationException | RuntimeException e) {
            throw new ConfigurationException("Failed to create a transformer from the file " + xslFile + ".", e);
        }
    }

}
